### ISSUE TITLE
Update Dockerhub image to 1.7.5 and ENV parameter for skin?

### ISSUE THREAD

**Issue by poVoq** [ether/etherpad-docker#11]
https://hub.docker.com/r/etherpad/etherpad
Has not been updated since 3 months and is also missing documentation of version tags.

Would be nice if a new 1.7.5 release could be done.

Any chance to have a ENV parameter to set the new skin?

Thanks a lot!

**Comment by muxator** [comment]
Hi, the Docker image will be updated asap. I see this manual process as a temporary solution, because moving forward I would like to have an automated pipeline.

Regarding ENV variables for configuration. We'll hold on for 1.7.5, because a generalized solution is on the roadmap for 1.8, see https://github.com/ether/etherpad-lite/issues/3543.
